
card_types= ["cavalry", "infantry", "artillery"];
card_type_maxlength= max(len(str) for str in card_types);

# dict of the territory cards
deck= [
    {'id':  0, 'territory': "Afghanistan",            'type': "cavalry"},
    {'id':  1, 'territory': "Alaska",                 'type': "infantry"},
    {'id':  2, 'territory': "Alberta",                'type': "cavalry"},
    {'id':  3, 'territory': "Argentina",              'type': "infantry"},
    {'id':  4, 'territory': "Brazil",                 'type': "artillery"},
    {'id':  5, 'territory': "Central Africa",         'type': "infantry"},
    {'id':  6, 'territory': "Central America",        'type': "artillery"},
    {'id':  7, 'territory': "China",                  'type': "infantry"},
    {'id':  8, 'territory': "East Africa",            'type': "infantry"},
    {'id':  9, 'territory': "Eastern Australia",      'type': "artillery"},
    {'id': 10, 'territory': "Eastern Canada",         'type': "cavalry"},
    {'id': 11, 'territory': "Eastern United States",  'type': "artillery"},
    {'id': 12, 'territory': "Egypt",                  'type': "infantry"},
    {'id': 13, 'territory': "Great Britian",          'type': "artillery"},
    {'id': 14, 'territory': "Greenland",              'type': "cavalry"},
    {'id': 15, 'territory': "Iceland",                'type': "infantry"},
    {'id': 16, 'territory': "India",                  'type': "cavalry"},
    {'id': 17, 'territory': "Indonesia",              'type': "artillery"},
    {'id': 18, 'territory': "Irkutsk",                'type': "cavalry"},
    {'id': 19, 'territory': "Japan",                  'type': "artillery"},
    {'id': 20, 'territory': "Kamchatka",              'type': "infantry"},
    {'id': 21, 'territory': "Madagascar",             'type': "cavalry"},
    {'id': 22, 'territory': "Middle East",            'type': "infantry"},
    {'id': 23, 'territory': "Mongolia",               'type': "infantry"},
    {'id': 24, 'territory': "New Guinea",             'type': "infantry"},
    {'id': 25, 'territory': "North Africa",           'type': "cavalry"},
    {'id': 26, 'territory': "Northern Europe",        'type': "artillery"},
    {'id': 27, 'territory': "Northwest Territory",    'type': "artillery"},
    {'id': 28, 'territory': "Ontario",                'type': "cavalry"},
    {'id': 29, 'territory': "Peru",                   'type': "infantry"},
    {'id': 30, 'territory': "Russia",                 'type': "cavalry"},
    {'id': 31, 'territory': "Scandinavia",            'type': "cavalry"},
    {'id': 32, 'territory': "Siberia",                'type': "cavalry"},
    {'id': 33, 'territory': "South Africa",           'type': "artillery"},
    {'id': 34, 'territory': "Southeast Asia",         'type': "infantry"},
    {'id': 35, 'territory': "Southern Europe",        'type': "artillery"},
    {'id': 36, 'territory': "Ural",                   'type': "cavalry"},
    {'id': 37, 'territory': "Venezuela",              'type': "infantry"},
    {'id': 38, 'territory': "Western Australia",      'type': "artillery"},
    {'id': 39, 'territory': "Western Europe",         'type': "artillery"},
    {'id': 40, 'territory': "Western United States",  'type': "artillery"},
    {'id': 41, 'territory': "Yakutsk",                'type': "cavalry"},
    {'id': 42, 'territory': None,                     'type': "wild"},
    {'id': 43, 'territory': None,                     'type': "wild"},
];
